service: coding-challenge

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: ${env:AWS_DEFAULT_REGION, "us-east-1"}
  stage: ${env:STAGE, "dev"}
  runtime: nodejs8.10

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn

package:
  individually: true

functions:
  shows-filter:
    handler: src/endpoints/shows-filter/index.handler
    events:
      - http:
          path: /
          method: post
          cors: true
